/*============================================================================
   Oil & Gas Upstream Operations Demo - Environment Setup
   
   Purpose: Creates database, schema, and all required tables
   Duration: ~3-4 minutes
   
   Execute this script first as ACCOUNTADMIN or with sufficient privileges
============================================================================*/

-- Set context
USE ROLE ACCOUNTADMIN;

-- Create warehouse for demo (if not exists)
CREATE WAREHOUSE IF NOT EXISTS DEMO_WH WITH
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 90
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Demo Warehouse';

USE WAREHOUSE DEMO_WH;

-- Create database and schema
CREATE DATABASE IF NOT EXISTS OIL_GAS_UPSTREAM_DEMO
  COMMENT = 'Demo database for Snowflake Intelligence - Oil & Gas Upstream';

CREATE SCHEMA IF NOT EXISTS OIL_GAS_UPSTREAM_DEMO.OPERATIONS
  COMMENT = 'Operational data for upstream oil & gas';

USE DATABASE OIL_GAS_UPSTREAM_DEMO;
USE SCHEMA OPERATIONS;

-- Table 1: Wells Master Data
CREATE OR REPLACE TABLE WELLS (
    WELL_ID VARCHAR(50) PRIMARY KEY,
    WELL_NAME VARCHAR(100),
    FIELD_NAME VARCHAR(100),
    OPERATOR VARCHAR(100),
    WELL_TYPE VARCHAR(20), -- Vertical, Horizontal, Deviated
    WELL_STATUS VARCHAR(20), -- Active, Inactive, Shut-in, Abandoned
    SPUD_DATE DATE,
    COMPLETION_DATE DATE,
    TOTAL_DEPTH_FT NUMBER(10,2),
    MEASURED_DEPTH_FT NUMBER(10,2),
    LATERAL_LENGTH_FT NUMBER(10,2),
    SURFACE_LATITUDE NUMBER(10,6),
    SURFACE_LONGITUDE NUMBER(10,6),
    FORMATION VARCHAR(100),
    RESERVOIR_NAME VARCHAR(100),
    DRILLING_COST_USD NUMBER(15,2),
    COMPLETION_COST_USD NUMBER(15,2),
    ESTIMATED_RESERVES_BOE NUMBER(15,2),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Table 2: Daily Production Data
CREATE OR REPLACE TABLE DAILY_PRODUCTION (
    PRODUCTION_ID VARCHAR(50) PRIMARY KEY,
    WELL_ID VARCHAR(50),
    PRODUCTION_DATE DATE,
    OIL_BBL NUMBER(10,2), -- Oil in barrels
    GAS_MCF NUMBER(10,2), -- Gas in thousand cubic feet
    WATER_BBL NUMBER(10,2), -- Water production in barrels
    BOE NUMBER(10,2), -- Barrels of oil equivalent
    TUBING_PRESSURE_PSI NUMBER(8,2),
    CASING_PRESSURE_PSI NUMBER(8,2),
    CHOKE_SIZE_64THS NUMBER(5,2),
    RUNTIME_HOURS NUMBER(5,2),
    DOWNTIME_HOURS NUMBER(5,2),
    PRODUCTION_METHOD VARCHAR(50), -- Natural flow, Gas lift, ESP, Rod pump
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (WELL_ID) REFERENCES WELLS(WELL_ID)
);

-- Table 3: Well Operations and Costs
CREATE OR REPLACE TABLE WELL_OPERATIONS (
    OPERATION_ID VARCHAR(50) PRIMARY KEY,
    WELL_ID VARCHAR(50),
    OPERATION_DATE DATE,
    OPERATION_TYPE VARCHAR(100), -- Workover, Stimulation, Maintenance, Inspection
    OPERATION_DESCRIPTION VARCHAR(500),
    DURATION_HOURS NUMBER(8,2),
    LABOR_COST_USD NUMBER(12,2),
    MATERIAL_COST_USD NUMBER(12,2),
    EQUIPMENT_COST_USD NUMBER(12,2),
    TOTAL_COST_USD NUMBER(12,2),
    VENDOR VARCHAR(100),
    SUCCESS_FLAG BOOLEAN,
    PRODUCTION_IMPACT_BOE NUMBER(10,2), -- Incremental production gained
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (WELL_ID) REFERENCES WELLS(WELL_ID)
);

-- Table 4: Equipment Assets
CREATE OR REPLACE TABLE EQUIPMENT_ASSETS (
    ASSET_ID VARCHAR(50) PRIMARY KEY,
    ASSET_NAME VARCHAR(200),
    ASSET_TYPE VARCHAR(100), -- Pump, Compressor, Separator, Tank, Wellhead
    WELL_ID VARCHAR(50),
    FACILITY_NAME VARCHAR(100),
    MANUFACTURER VARCHAR(100),
    MODEL VARCHAR(100),
    SERIAL_NUMBER VARCHAR(100),
    INSTALL_DATE DATE,
    DESIGN_LIFE_YEARS NUMBER(5,2),
    REPLACEMENT_COST_USD NUMBER(15,2),
    LAST_MAINTENANCE_DATE DATE,
    NEXT_MAINTENANCE_DATE DATE,
    CRITICALITY VARCHAR(20), -- Critical, High, Medium, Low
    STATUS VARCHAR(20), -- Operational, Degraded, Failed, Maintenance
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (WELL_ID) REFERENCES WELLS(WELL_ID)
);

-- Table 5: Equipment Failures and Downtime
CREATE OR REPLACE TABLE EQUIPMENT_FAILURES (
    FAILURE_ID VARCHAR(50) PRIMARY KEY,
    ASSET_ID VARCHAR(50),
    WELL_ID VARCHAR(50),
    FAILURE_DATE TIMESTAMP,
    DETECTION_METHOD VARCHAR(100), -- Alarm, Inspection, Production anomaly
    FAILURE_MODE VARCHAR(200),
    FAILURE_CAUSE VARCHAR(500),
    SEVERITY VARCHAR(20), -- Critical, Major, Minor
    DOWNTIME_HOURS NUMBER(8,2),
    REPAIR_COST_USD NUMBER(12,2),
    PRODUCTION_LOSS_BOE NUMBER(10,2),
    RESOLVED_DATE TIMESTAMP,
    ROOT_CAUSE VARCHAR(500),
    CORRECTIVE_ACTION VARCHAR(500),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (ASSET_ID) REFERENCES EQUIPMENT_ASSETS(ASSET_ID),
    FOREIGN KEY (WELL_ID) REFERENCES WELLS(WELL_ID)
);

-- Table 6: Reservoir Data
CREATE OR REPLACE TABLE RESERVOIR_DATA (
    RESERVOIR_ID VARCHAR(50) PRIMARY KEY,
    RESERVOIR_NAME VARCHAR(100),
    FIELD_NAME VARCHAR(100),
    FORMATION VARCHAR(100),
    DISCOVERY_DATE DATE,
    RESERVOIR_TYPE VARCHAR(50), -- Oil, Gas, Condensate
    INITIAL_PRESSURE_PSI NUMBER(8,2),
    CURRENT_PRESSURE_PSI NUMBER(8,2),
    PRESSURE_DEPLETION_PCT NUMBER(5,2),
    POROSITY_PCT NUMBER(5,2),
    PERMEABILITY_MD NUMBER(10,2),
    OIL_SATURATION_PCT NUMBER(5,2),
    WATER_SATURATION_PCT NUMBER(5,2),
    NET_PAY_FT NUMBER(8,2),
    AREA_ACRES NUMBER(10,2),
    OOIP_MMSTB NUMBER(12,2), -- Original oil in place
    RECOVERABLE_RESERVES_MMSTB NUMBER(12,2),
    RECOVERY_FACTOR_PCT NUMBER(5,2),
    CUMULATIVE_PRODUCTION_MMSTB NUMBER(12,2),
    REMAINING_RESERVES_MMSTB NUMBER(12,2),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Table 7: Reservoir Pressure Monitoring
CREATE OR REPLACE TABLE RESERVOIR_PRESSURE (
    MEASUREMENT_ID VARCHAR(50) PRIMARY KEY,
    RESERVOIR_ID VARCHAR(50),
    WELL_ID VARCHAR(50),
    MEASUREMENT_DATE DATE,
    PRESSURE_PSI NUMBER(8,2),
    TEMPERATURE_F NUMBER(6,2),
    MEASUREMENT_DEPTH_FT NUMBER(10,2),
    MEASUREMENT_METHOD VARCHAR(50), -- Gauge, Test, Simulation
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (RESERVOIR_ID) REFERENCES RESERVOIR_DATA(RESERVOIR_ID),
    FOREIGN KEY (WELL_ID) REFERENCES WELLS(WELL_ID)
);

-- Table 8: HSE Incidents (Health, Safety, Environment)
CREATE OR REPLACE TABLE HSE_INCIDENTS (
    INCIDENT_ID VARCHAR(50) PRIMARY KEY,
    INCIDENT_DATE TIMESTAMP,
    FACILITY_NAME VARCHAR(100),
    WELL_ID VARCHAR(50),
    INCIDENT_TYPE VARCHAR(50), -- Safety, Environmental, Near-miss
    INCIDENT_CATEGORY VARCHAR(100), -- Spill, Injury, Fire, Gas release
    SEVERITY VARCHAR(20), -- Fatal, Serious, Minor, Near-miss
    DESCRIPTION VARCHAR(1000),
    INJURIES NUMBER(5),
    FATALITIES NUMBER(5),
    VOLUME_SPILLED_BBL NUMBER(10,2),
    REGULATORY_REPORTABLE BOOLEAN,
    DAYS_AWAY_FROM_WORK NUMBER(5),
    ESTIMATED_COST_USD NUMBER(12,2),
    ROOT_CAUSE VARCHAR(500),
    CORRECTIVE_ACTIONS VARCHAR(1000),
    INVESTIGATION_STATUS VARCHAR(50),
    CLOSED_DATE DATE,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (WELL_ID) REFERENCES WELLS(WELL_ID)
);

-- Table 9: Drilling and Capital Projects
CREATE OR REPLACE TABLE DRILLING_PROJECTS (
    PROJECT_ID VARCHAR(50) PRIMARY KEY,
    PROJECT_NAME VARCHAR(200),
    WELL_ID VARCHAR(50),
    FIELD_NAME VARCHAR(100),
    PROJECT_TYPE VARCHAR(50), -- New drill, Workover, Facility, Pipeline
    PROJECT_STATUS VARCHAR(50), -- Planned, In Progress, Completed, Cancelled
    PLANNED_START_DATE DATE,
    ACTUAL_START_DATE DATE,
    PLANNED_COMPLETION_DATE DATE,
    ACTUAL_COMPLETION_DATE DATE,
    BUDGETED_COST_USD NUMBER(15,2),
    ACTUAL_COST_USD NUMBER(15,2),
    COST_VARIANCE_PCT NUMBER(5,2),
    EXPECTED_PRODUCTION_BOEPD NUMBER(10,2), -- Barrels of oil equivalent per day
    EXPECTED_EUR_BOE NUMBER(15,2), -- Estimated ultimate recovery
    NPV_USD NUMBER(15,2),
    IRR_PCT NUMBER(5,2),
    PAYBACK_MONTHS NUMBER(5,2),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (WELL_ID) REFERENCES WELLS(WELL_ID)
);

-- Table 10: Supply Chain and Materials
CREATE OR REPLACE TABLE SUPPLY_CHAIN (
    TRANSACTION_ID VARCHAR(50) PRIMARY KEY,
    TRANSACTION_DATE DATE,
    MATERIAL_TYPE VARCHAR(100), -- Casing, Tubing, Chemicals, Parts
    MATERIAL_DESCRIPTION VARCHAR(500),
    VENDOR VARCHAR(100),
    QUANTITY NUMBER(10,2),
    UNIT_OF_MEASURE VARCHAR(20),
    UNIT_COST_USD NUMBER(12,2),
    TOTAL_COST_USD NUMBER(12,2),
    WELL_ID VARCHAR(50),
    PROJECT_ID VARCHAR(50),
    DELIVERY_DATE DATE,
    LEAD_TIME_DAYS NUMBER(5),
    ON_TIME_DELIVERY BOOLEAN,
    QUALITY_RATING NUMBER(3,2), -- 1-5 scale
    STOCK_LEVEL NUMBER(10,2),
    REORDER_POINT NUMBER(10,2),
    CRITICALITY VARCHAR(20),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (WELL_ID) REFERENCES WELLS(WELL_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES DRILLING_PROJECTS(PROJECT_ID)
);

-- Table 11: Emissions and Environmental Data
CREATE OR REPLACE TABLE EMISSIONS_DATA (
    EMISSION_ID VARCHAR(50) PRIMARY KEY,
    MEASUREMENT_DATE DATE,
    FACILITY_NAME VARCHAR(100),
    WELL_ID VARCHAR(50),
    EMISSION_TYPE VARCHAR(50), -- CO2, Methane, VOC, NOx, Flaring
    EMISSION_SOURCE VARCHAR(100), -- Combustion, Venting, Flaring, Fugitive
    QUANTITY_TONNES NUMBER(12,4),
    QUANTITY_CO2E_TONNES NUMBER(12,4), -- CO2 equivalent
    MEASUREMENT_METHOD VARCHAR(50), -- Direct, Calculated, Estimated
    PRODUCTION_BOE NUMBER(10,2), -- For intensity calculation
    EMISSION_INTENSITY NUMBER(10,4), -- tonnes CO2e per BOE
    REGULATORY_LIMIT NUMBER(12,4),
    COMPLIANCE_STATUS VARCHAR(20), -- Compliant, Warning, Violation
    MITIGATION_ACTIONS VARCHAR(500),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (WELL_ID) REFERENCES WELLS(WELL_ID)
);

-- Create indexes for performance
-- CREATE INDEX idx_daily_prod_well_date ON DAILY_PRODUCTION(WELL_ID, PRODUCTION_DATE);
-- CREATE INDEX idx_operations_well_date ON WELL_OPERATIONS(WELL_ID, OPERATION_DATE);
-- CREATE INDEX idx_failures_asset_date ON EQUIPMENT_FAILURES(ASSET_ID, FAILURE_DATE);
-- CREATE INDEX idx_hse_date ON HSE_INCIDENTS(INCIDENT_DATE);
-- CREATE INDEX idx_emissions_date ON EMISSIONS_DATA(MEASUREMENT_DATE);

-- Create views for common analytics
CREATE OR REPLACE VIEW VW_WELL_PERFORMANCE AS
SELECT 
    w.WELL_ID,
    w.WELL_NAME,
    w.FIELD_NAME,
    w.WELL_TYPE,
    w.WELL_STATUS,
    COUNT(DISTINCT dp.PRODUCTION_DATE) as DAYS_PRODUCING,
    SUM(dp.OIL_BBL) as TOTAL_OIL_BBL,
    SUM(dp.GAS_MCF) as TOTAL_GAS_MCF,
    SUM(dp.BOE) as TOTAL_BOE,
    AVG(dp.OIL_BBL) as AVG_DAILY_OIL,
    AVG(dp.BOE) as AVG_DAILY_BOE,
    SUM(wo.TOTAL_COST_USD) as TOTAL_OPEX,
    CASE 
        WHEN SUM(dp.BOE) > 0 THEN SUM(wo.TOTAL_COST_USD) / SUM(dp.BOE)
        ELSE NULL 
    END as OPEX_PER_BOE
FROM WELLS w
LEFT JOIN DAILY_PRODUCTION dp ON w.WELL_ID = dp.WELL_ID
LEFT JOIN WELL_OPERATIONS wo ON w.WELL_ID = wo.WELL_ID
GROUP BY w.WELL_ID, w.WELL_NAME, w.FIELD_NAME, w.WELL_TYPE, w.WELL_STATUS;

CREATE OR REPLACE VIEW VW_EQUIPMENT_RELIABILITY AS
SELECT 
    ea.ASSET_ID,
    ea.ASSET_NAME,
    ea.ASSET_TYPE,
    ea.WELL_ID,
    ea.CRITICALITY,
    COUNT(ef.FAILURE_ID) as FAILURE_COUNT,
    SUM(ef.DOWNTIME_HOURS) as TOTAL_DOWNTIME_HOURS,
    SUM(ef.REPAIR_COST_USD) as TOTAL_REPAIR_COST,
    SUM(ef.PRODUCTION_LOSS_BOE) as TOTAL_PRODUCTION_LOSS,
    AVG(ef.DOWNTIME_HOURS) as AVG_DOWNTIME_PER_FAILURE
FROM EQUIPMENT_ASSETS ea
LEFT JOIN EQUIPMENT_FAILURES ef ON ea.ASSET_ID = ef.ASSET_ID
GROUP BY ea.ASSET_ID, ea.ASSET_NAME, ea.ASSET_TYPE, ea.WELL_ID, ea.CRITICALITY;

-- Grant permissions (adjust as needed for your environment)
GRANT USAGE ON DATABASE OIL_GAS_UPSTREAM_DEMO TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA OIL_GAS_UPSTREAM_DEMO.OPERATIONS TO ROLE PUBLIC;
GRANT SELECT ON ALL TABLES IN SCHEMA OIL_GAS_UPSTREAM_DEMO.OPERATIONS TO ROLE PUBLIC;
GRANT SELECT ON ALL VIEWS IN SCHEMA OIL_GAS_UPSTREAM_DEMO.OPERATIONS TO ROLE PUBLIC;

SELECT 'Environment setup completed successfully!' AS STATUS;
SELECT 'Database: OIL_GAS_UPSTREAM_DEMO' AS INFO;
SELECT 'Schema: OPERATIONS' AS INFO;
SELECT 'Tables created: 11' AS INFO;
SELECT 'Views created: 2' AS INFO;

